### ISSUE TITLE
IDA hangs if you search "too fast"

### ISSUE THREAD

**Issue by sferrini** [Ga-ryo/IDAFuzzy#1]
Hi @Ga-ryo,

Thanks for this plugin, nice idea.

I just wanted to report an issue I noticed: in big binaries (with a lot of symbols), if you type fast in the IDAFuzzy search form, the IDA GUI hangs and will never recover. So you have to kill and restart IDA.

I guess it's because IDA callbacks the plugin (every char) but the plugin hasn't finished yet to filtering.

Let me know if you need more info,

Thanks.

**Comment by Ga-ryo** [comment]
Hi, @sferrini 
Thank you for using my plugin and create issue!

I  fixed  the issue with the commit below.
https://github.com/Ga-ryo/IDAFuzzy/commit/09436adbabf6dd6d4beb7da5bed10c56f9c53419
https://github.com/Ga-ryo/IDAFuzzy/commit/9d07b151feb1f624d0399d762cb69fdf4b3929b4

Can you check  if IDA hangs or not? 
I tested with EXE > 100MB(many symbol) and typed meaninglessly speedy, then IDA didn't crashed.

**Comment by Ga-ryo** [comment]
umm...

Still I could cause crash in rare cases. X(

**Comment by sferrini** [comment]
Hey @Ga-ryo I've tested a big `mach-o`, and I couldn't reproduce the issue with the latest commits.
I'll let you know if I can crash it working with bigger binaries ;)

Thanks for taking the time to review the issue and to push fixes!

**Comment by Ga-ryo** [comment]
@sferrini 
If you type 6\~8 char at the same time(with 6\~8 finger).
It has crashed. (at the commit of 30 minutes ago)
But maybe I could fixed.

Thank you for your help!
