### ISSUE TITLE
Compatibility with IDA 7.4 and Python3

### ISSUE THREAD

**Issue by evolution536** [Ga-ryo/IDAFuzzy#6]
The 'idc.Demangle' function can be replaced by 'idc.demangle_name' and the 'GetLongPrm' function by 'get_inf_attr'. However, more things such as 'xrange' -> 'range' should be fixed, and the UI objects are missing functions or attributes. Could you change the missing things such that the plugin works with IDA 7.4 and Python3?

**Comment by Ga-ryo** [comment]
Thank you for pointing it out.
But unfortunately, I don't have a license for latest IDA Pro 😢
If you create PR for this issue, I appreciate it.

**Comment by evolution536** [comment]
I created a pull request with the script that seems to work in my IDA 7.4 installation! :)
